package tcu.backend.cars.service_impl;

public enum CarAPIResponseForClient {
    NO_RESPONSE,
    GET_CAR_BY_VIN_SUCCESS,
    GET_CAR_BY_VIN_NOT_FOUND,
    SECURITY_KEY_NOT_MATCH,
    RETRIEVE_CAR_FROM_DATABASE_FAILED,
    CAR_ALREADY_LINKED_TO_AN_ACCOUNT,
    TOKEN_VALIDATION_FAILED,
    TOKEN_SUCCESSFULLY_VALIDATED,
    LINKAGE_TO_ACCOUNT_SUCCESS

}
